### ISSUE TITLE
Distancia entre dos puntos (Cabecera: public double getDistance(Point p))

### ISSUE THREAD

**Issue by kikevillab** [kikevillab/IWVG.SwC.EnriqueArranz#1]
Dado un punto se calcular la distancia a otro punto en el plano.

Consultar la wiki para ver la [guia de buenas practicas](https://github.com/kikevillab/IWVG.SwC.EnriqueArranz/wiki/Guia-de-buenas-practicas) y la [mejora](https://github.com/kikevillab/IWVG.SwC.EnriqueArranz/wiki/Mejoras#1---distancia-entre-dos-puntos-cabecera-public-double-getdistancepoint-p).

**Comment by kikevillab** [comment]
He ampliado el tiempo para el hito hasta el lunes. Si necesitas mas tiempo o no vas a poder hacerlo dimelo.
Si tienes algun problema tambien dimelo.

**Comment by fclopezjurado** [comment]
Realizada Mejora #1.

El commit associado, para tenerlo como referencia es c4193f833d2fb7aa6f036437c016249231bb5876
Incluido en la rama develop, tras el merge realizado en f28a7a5f999f7db0ae1ce03a12b3c448a713d962

Un saludo!

Fran

**Comment by kikevillab** [comment]
PErfecto Thx
