### ISSUE TITLE
Añadir método slice a DecimalCollection (Cabecera: public void slice(Double i))

### ISSUE THREAD

**Issue by kikevillab** [kikevillab/IWVG.SwC.EnriqueArranz#3]
Mediante el metodo remove de la interfaz List.

Consultar la wiki para ver la [guia de buenas practicas](https://github.com/kikevillab/IWVG.SwC.EnriqueArranz/wiki/Guia-de-buenas-practicas) y la [mejora](https://github.com/kikevillab/IWVG.SwC.EnriqueArranz/wiki/Mejoras#3---a%C3%B1adir-m%C3%A9todo-slice-a-decimalcollection-cabecera-public-void-slicedouble-i).

Cualquier duda, poner comentario

**Comment by JorgeHigueraFombuena** [comment]
Hola
Tengo una duda con este método
El método recibe como parámetro un Double. Ese Double es la posición del array o el elemento?
Un saludo
J.

**Comment by kikevillab** [comment]
El elemento que recibe como parametro es el elemento a eliminar, si fuese la posicion tendria mas sentido que fuese un int, voy a modificar la wiki para que se entienda mejor.

**Comment by JorgeHigueraFombuena** [comment]
Hola
Sí, lo pensé luego. Pero en un principio no me había quedado claro
Muchas gracias
Un saludo
J.

**Comment by kikevillab** [comment]
Ya lo he visto y esta bien.

Thx
