### ISSUE TITLE
Comparar si dos fracciones son equivalentes (Cabecera: public boolean equals(Fraction f))

### ISSUE THREAD

**Issue by kikevillab** [kikevillab/IWVG.SwC.EnriqueArranz#4]
Mediante el metodo decimals.

Consultar la wiki para ver la [guia de buenas practicas](https://github.com/kikevillab/IWVG.SwC.EnriqueArranz/wiki/Guia-de-buenas-practicas) y la [mejora](https://github.com/kikevillab/IWVG.SwC.EnriqueArranz/wiki/Mejoras#4---comparar-si-dos-fracciones-son-equivalentes-cabecera-public-boolean-equalsfraction-f).

Cualquier duda, poner comentario

**Comment by JorgeHigueraFombuena** [comment]
Hecho y subido 
Espero que esté todo correcto ;)
Un saludo
J.

**Comment by kikevillab** [comment]
A la noche lo reviso. Thx

**Comment by kikevillab** [comment]
Perfecto esta todo correcto. Cierro el issue
