### ISSUE TITLE
Fraccion inversa (Cabecera: public Fraction inverse())

### ISSUE THREAD

**Issue by kikevillab** [kikevillab/IWVG.SwC.EnriqueArranz#6]
Devolver la inversa de una fraccion.

Consultar la wiki para ver la [guia de buenas practicas](https://github.com/kikevillab/IWVG.SwC.EnriqueArranz/wiki/Guia-de-buenas-practicas) y la [mejora](https://github.com/kikevillab/IWVG.SwC.EnriqueArranz/wiki/Mejoras#6---devolver-una-nueva-fraccion-inversa-cabecera-public-fraction-inverse).

Cualquier duda, poner comentario

**Comment by kikevillab** [comment]
He ampliado el tiempo para el hito hasta el lunes. Si necesitas mas tiempo o no vas a poder hacerlo dimelo.
Si tienes algun problema tambien dimelo.

**Comment by fclopezjurado** [comment]
Ok, mañana le meto mano y te lo dejo listo ;-)

**Comment by fclopezjurado** [comment]
Realizada Mejora #6.

El commit associado, para tenerlo como referencia es 1aaa5c2c1ad379094e89baec647fa7518e81ee09
Incluido en la rama develop, tras el merge realizado en dcd1d0f90f6b25a1d33cbc96bc5627df116d831f

Un saludo!

Fran

**Comment by kikevillab** [comment]
PErfecto! Thx
